background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 4
    blur_size = 10
    brightness = 0.4
    contrast = 0.68
    vibrancy = 0.0
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 420, 60
    outline_thickness = 2
    font_color = rgba(242, 243, 244, 0.75)
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    fade_on_empty = false
    check_color = rgb(204, 136, 34)
    placeholder_text = <span alpha="50%"><i>Press Enter for face unlock, or type your password</i></span>
    hide_input = false
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 100
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = JetBrains Mono
  position = 0, 200
  halign = center
  valign = center
}
